Repository woowacourse-integrated-service/techhub, pull requests merged in 2023-09, with the labels that each got.

#1 settings: ISSUE/PR Template
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/meeting.yml
  .github/ISSUE_TEMPLATE/refactor.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/gradle.yml
  .idea/git_toolbox_prj.xml
Labels: documentation

#5 settings: gitignore 추가
  .github/workflows/gradle.yml
  .gitignore
  .gradle/8.2.1/checksums/checksums.lock
  .gradle/8.2.1/dependencies-accessors/dependencies-accessors.lock
  .gradle/8.2.1/dependencies-accessors/gc.properties
  .gradle/8.2.1/executionHistory/executionHistory.lock
  .gradle/8.2.1/fileChanges/last-build.bin
  .gradle/8.2.1/fileHashes/fileHashes.lock
  .gradle/8.2.1/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/vcs-1/gc.properties
  .idea/gradle.xml
  .idea/modules.xml
  .idea/modules/techhub.main.iml
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: ⚙️ Setting

#8 feat: Github Pull Request 조회
  build.gradle
  src/main/java/com/integrated/techhub/common/config/QuerydslConfig.java
  src/main/java/com/integrated/techhub/pr/application/PullRequestQueryService.java
  src/main/java/com/integrated/techhub/pr/domain/PullRequest.java
  src/main/java/com/integrated/techhub/pr/domain/repository/PullRequestQueryRepository.java
  src/main/java/com/integrated/techhub/pr/domain/repository/PullRequestRepository.java
  src/main/java/com/integrated/techhub/pr/domain/type/Status.java
  src/main/java/com/integrated/techhub/pr/dto/response/GetPullRequestResponse.java
  src/main/java/com/integrated/techhub/pr/presentation/PullRequestController.java
  src/test/java/com/integrated/techhub/common/acceptance/AcceptanceSteps.java
  src/test/java/com/integrated/techhub/common/acceptance/AcceptanceTest.java
  src/test/java/com/integrated/techhub/common/config/QuerydslConfig.java
  src/test/java/com/integrated/techhub/pr/application/PullRequestQueryServiceTest.java
  src/test/java/com/integrated/techhub/pr/domain/fixture/PullRequestFixture.java
  src/test/java/com/integrated/techhub/pr/domain/repository/PullRequestRepositoryTest.java
  src/test/java/com/integrated/techhub/pr/presentation/PullRequestControllerSteps.java
  src/test/java/com/integrated/techhub/pr/presentation/PullRequestControllerTest.java
  src/test/resources/truncate.sql
Labels: ✨ Feature

#7 feat:Member, AuthorityCode 생성
  build.gradle
  lombok.config
  src/main/java/com/integrated/techhub/common/config/RedisConfig.java
  src/main/java/com/integrated/techhub/member/domain/AuthorityCode.java
  src/main/java/com/integrated/techhub/member/domain/Member.java
  src/main/java/com/integrated/techhub/member/domain/Position.java
  src/main/java/com/integrated/techhub/member/domain/repository/AuthorityCodeRepository.java
  src/main/java/com/integrated/techhub/member/domain/repository/MemberRepository.java
  src/main/resources/application.yml
  src/test/java/com/integrated/techhub/TechhubApplicationTests.java
  src/test/java/com/integrated/techhub/member/domain/AuthorityCodeTest.java
  src/test/java/com/integrated/techhub/member/domain/MemberTest.java
  src/test/resources/application.yml
Labels: ✨ Feature

#10 feat: 회원가입 기능 추가
  .gitignore
  build.gradle
  src/main/java/com/integrated/techhub/auth/application/AuthQueryService.java
  src/main/java/com/integrated/techhub/auth/application/AuthService.java
  src/main/java/com/integrated/techhub/auth/domain/PasswordEncoder.java
  src/main/java/com/integrated/techhub/auth/dto/SignUpRequest.java
  src/main/java/com/integrated/techhub/auth/infra/encode/BCryptPasswordEncoder.java
  src/main/java/com/integrated/techhub/auth/presentation/AuthController.java
  src/main/java/com/integrated/techhub/common/config/AsyncConfig.java
  src/main/java/com/integrated/techhub/common/config/EmbeddedRedisConfig.java
  src/main/java/com/integrated/techhub/common/exception/ErrorCode.java
  src/main/java/com/integrated/techhub/common/exception/ErrorResponse.java
  src/main/java/com/integrated/techhub/common/exception/TechHubException.java
  src/main/java/com/integrated/techhub/mail/application/MailService.java
  src/main/java/com/integrated/techhub/mail/domain/AuthorityCode.java
  src/main/java/com/integrated/techhub/mail/domain/AuthorityCodeRepository.java
  src/main/java/com/integrated/techhub/mail/domain/ITemplateEngine.java
  src/main/java/com/integrated/techhub/mail/domain/type/MailInfo.java
  src/main/java/com/integrated/techhub/mail/dto/MailSendRequest.java
  src/main/java/com/integrated/techhub/mail/dto/MailValidateRequest.java
  src/main/java/com/integrated/techhub/mail/exception/AuthorityCodeNotFoundException.java
  src/main/java/com/integrated/techhub/mail/exception/AuthorityCodeNotMatchException.java
  src/main/java/com/integrated/techhub/mail/infra/mail/SpringTemplateEngineWrapper.java
  src/main/java/com/integrated/techhub/mail/presentation/MailController.java
  src/main/java/com/integrated/techhub/member/domain/Member.java
  src/main/java/com/integrated/techhub/member/domain/repository/MemberRepository.java
  src/main/java/com/integrated/techhub/member/exception/MemberExistsException.java
  src/main/resources/application.yml
  src/main/resources/templates/mail.html
  src/test/java/com/integrated/techhub/TechhubApplicationTests.java
  src/test/java/com/integrated/techhub/auth/application/AuthQueryServiceTest.java
  src/test/java/com/integrated/techhub/auth/application/AuthServiceTest.java
  src/test/java/com/integrated/techhub/auth/infra/encode/BCryptPasswordEncoderTest.java
  src/test/java/com/integrated/techhub/auth/presentation/AuthControllerTest.java
  src/test/java/com/integrated/techhub/common/acceptance/AcceptanceTest.java
  src/test/java/com/integrated/techhub/mail/application/MailServiceMockTest.java
  src/test/java/com/integrated/techhub/mail/application/MailServiceTest.java
  src/test/java/com/integrated/techhub/mail/domain/type/MailInfoTest.java
  src/test/java/com/integrated/techhub/mail/infra/mail/TestTemplateEngineWrapper.java
  src/test/java/com/integrated/techhub/mail/presentation/MailControllerMockTest.java
  src/test/java/com/integrated/techhub/mail/presentation/MailControllerSteps.java
  src/test/java/com/integrated/techhub/mail/presentation/MailControllerTest.java
  src/test/java/com/integrated/techhub/member/domain/AuthorityCodeTest.java
  src/test/java/com/integrated/techhub/member/domain/MemberTest.java
  src/test/java/com/integrated/techhub/member/fixture/MemberFixture.java
  src/test/resources/application.yml
Labels: ✨ Feature
